name: Request Game
description: Request a new game to be added
title: "<Game Name>"

body:
  - type: input
    id: game
    attributes:
      label: Game Title
      placeholder: e.g. Team Fortress 2
    validations:
      required: true
  - type: input
    id: anti-cheat
    attributes:
      label: Anti-Cheat Software
      placeholder: e.g. Easy Anti-Cheat
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Current Status
      description: In what status is the anti-cheat support right now?
      options:
        - Denied
        - Broken
        - Running
        - Planned
        - Supported
    validations:
      required: true
  - type: input
    id: reference
    attributes:
      label: Reference
      description: A reputable link where the developers either confirmed or denied the chance of support happening. If non-applicable, just put N/A.
      placeholder: e.g. https://www.theverge.com/2021/10/5/22709918/valve-steam-deck-supported-games-anti-cheat-proton-eac-battleye-epic
    validations:
      required: true
