name: Update Game
description: Request changes for a game on the list
title: "Update <Game Name>"

body:
  - type: input
    id: game
    attributes:
      label: Game Title
      placeholder: e.g. Team Fortress 2
    validations:
      required: true
  - type: input
    id: anti-cheat-changes
    attributes:
      label: Anti-Cheat Software Changes
      placeholder: e.g. Easy Anti-Cheat
  - type: dropdown
    id: new-status
    attributes:
      label: New Status
      description: Did the anti-cheat status change?
      options:
        - Denied
        - Broken
        - Running
        - Planned
        - Supported
  - type: input
    id: new-reference
    attributes:
      label: Reference
      description: A reputable link where the developers either confirmed or denied the chance of support happening. If non-applicable, just put N/A.
      placeholder: e.g. https://www.theverge.com/2021/10/5/22709918/valve-steam-deck-supported-games-anti-cheat-proton-eac-battleye-epic
